# Generated by Django 3.0.6 on 2020-06-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duocmobile', '0002_materialapoyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Alumno', 'Alumno'), ('Docente', 'Docente'), ('Admin', 'Admin')], default='Alumno', max_length=50),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='duocmobile.Perfil')),
            ],
        ),
    ]
