# Generated by Django 2.2.13 on 2020-06-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duocmobile', '0003_auto_20200615_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(choices=[(' ', ' '), ('INGENIERIA INFORMATICA', 'INGENIERIA INFORMATICA')], default='', max_length=500)),
                ('categoria', models.CharField(choices=[(' ', ' '), ('ACADEMICO', 'ACADEMICO'), ('FINANCIERO', 'FINANCIERO')], default='', max_length=500)),
                ('servicio', models.CharField(choices=[(' ', ' '), ('ACTUALIZACION DATOS', 'ACTUALIZACION DATOS'), ('CONVALIDACION ASIGNATURA', 'CONVALIDACION ASIGNATURA'), ('NOTA PENDIENTE', 'NOTA PENDIENTE'), ('RENUNCIA', 'RENUNCIA')], default='', max_length=500)),
                ('comentario', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
